# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Course', models.CharField(max_length=50)),
                ('Cuisine', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
            ],
        ),
    ]
