# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.6 on 2017-10-29 19:52
=======
# Generated by Django 1.11.6 on 2017-10-29 18:46
>>>>>>> e562f70646d2269359c3081e1b2a1b7de2f90e3c
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('ID', models.BigIntegerField(primary_key=True, serialize=False)),
<<<<<<< HEAD
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField()),
                ('course', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
=======
                ('Course', models.CharField(max_length=50)),
                ('Cuisine', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
>>>>>>> e562f70646d2269359c3081e1b2a1b7de2f90e3c
            ],
        ),
    ]
