# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantmanagementsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashier',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='ID',
        ),
        migrations.AddField(
            model_name='cashier',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
