# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurantmanagementsystem', '0002_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('course', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('price', models.FloatField()),
                ('food_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
