# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantmanagementsystem', '0002_auto_20171109_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
